# Generated by Django 3.0.8 on 2020-07-12 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.DateField(auto_now_add=True)),
                ('finish_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PauseTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(auto_now_add=True)),
                ('stop', models.DateField(null=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timers.Timer')),
            ],
        ),
    ]
